[platformio]
default_envs = node_lora_t3, gateway_tbeam
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  bblanchon/ArduinoJson@^7.2.1
build_flags =
  -D AGRO_LORA_FREQUENCY=915E6
  -D AGRO_PROTOCOL_VERSION=3
  -D AGRO_SENSOR_PROFILE=1
  -D AGRO_SOIL_MOISTURE_PIN=34
  -D AGRO_ULTRASONIC_TRIG_PIN=32
  -D AGRO_ULTRASONIC_ECHO_PIN=33

[env:node_lora_t3]
board = ttgo-lora32-v1
build_src_filter =
  +<node_lora_t3/>
  +<shared/>
  -<gateway_tbeam/>
  -<arduino_ide/>

[env:gateway_tbeam]
board = ttgo-t-beam
build_src_filter =
  +<gateway_tbeam/>
  +<shared/>
  -<node_lora_t3/>
  -<arduino_ide/>
