[platformio]
default_envs = node_lora_t3, gateway_tbeam

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  bblanchon/ArduinoJson@^7.2.1
build_flags =
  -D AGRO_LORA_FREQUENCY=915E6
  -D AGRO_PROTOCOL_VERSION=1

[env:node_lora_t3]
board = ttgo-lora32-v1
build_src_filter =
  +<../shared>
  +<node_lora_t3>

[env:gateway_tbeam]
board = ttgo-t-beam
build_src_filter =
  +<../shared>
  +<gateway_tbeam>
